# Generated by Django 3.1.2 on 2020-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='update',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
