# Generated by Django 3.1.2 on 2020-10-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201006_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update', to='projects.project'),
        ),
    ]
