# Generated by Django 3.1.2 on 2020-10-09 08:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_update_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=85, size=[450, 300], upload_to='updates'),
        ),
    ]
