# Generated by Django 3.1.2 on 2020-10-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201012_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='project',
            name='expiry',
            field=models.DateField(),
        ),
    ]
