# Generated by Django 3.1.2 on 2020-10-26 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20201025_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
