# Generated by Django 3.1.2 on 2020-10-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20201026_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
