# Generated by Django 3.1.2 on 2020-10-28 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_auto_20201026_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('ACC', 'Access'), ('CITI', 'CitiBank'), ('ECO', 'Ecobank'), ('FID', 'Fidelity'), ('FCMB', 'FCMB'), ('FBN', 'First Bank'), ('GTB', 'GTB'), ('HERITAGE', 'Heritage'), ('KEYSTONE', 'Keystone'), ('POLARIS', 'Polaris'), ('STANBIC', 'Stanbic IBTC'), ('STANDARD', 'Standard Chartered'), ('STERLING', 'Sterling'), ('UBA', 'UBA'), ('UBN', 'Union Bank'), ('FCMB', 'FCMB'), ('UNITY', 'Unity Bank'), ('WEMA', 'Wema Bank'), ('ZENITH', 'Zenith Bank')], default='ACC', max_length=12)),
                ('account_type', models.CharField(max_length=10)),
                ('account_number', models.IntegerField()),
                ('account_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
