# Generated by Django 3.1.2 on 2020-10-28 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_bankdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
