# Generated by Django 3.1.2 on 2020-10-29 20:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='id_card',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=85, size=[420, 300], upload_to='identification'),
        ),
    ]
