# Generated by Django 3.1.2 on 2020-10-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_bankdetail_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='bank',
            field=models.CharField(max_length=20),
        ),
    ]
