# Generated by Django 3.1.2 on 2020-11-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20201030_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='date',
            new_name='created',
        ),
    ]
