# Generated by Django 3.1.2 on 2020-11-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20201102_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('token', models.CharField(default='b0a1e771151aaba9429e6332afeb08c9554a0533b257ace538705af919612eea1f5698eb65f9b662b81ae2fceb292d594091dd7c93f3bd13d2f07576cb9ed369649ace19990f18968c0efffedb983d05c1a80328f633f262', max_length=200)),
                ('expiry', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created']},
        ),
    ]
