# Generated by Django 3.1.2 on 2020-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20201105_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='50a91423c40d2d2e9b704103d83589f39799063759f41e66a867d0e85eadaa9292e986f2e91f67479d79495f5da41d6741cdc9f1ef14d5ebeb3db0116dadbaf0eb572d04142265f46a250102e8b477904c557008ba3da83e', max_length=200),
        ),
    ]
