# Generated by Django 3.1.2 on 2020-11-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20201106_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='ba290cad194d04bf6785d92ff9f82344448726c2fc6832ba6da3550e9a11d7597a778822eaf0c5404062e9a9466e6ddd6325a22b47376361cd5e4496ee524bfc8a5deda76152b26b6ac3b62744164813c5f50100d89d0556', max_length=200),
        ),
    ]
