# Generated by Django 3.1.2 on 2020-11-14 10:01

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20201114_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='16cc26f80ab45cbcfed40927f547aeb890a7cb18b02d200cdd638ad8634883c22b446d306da9b5fd00e01e20c5b1d280f0eb889590f1c70e9e1eae298cf94c0468ab053f7337ce4a460bab7a308503d48981cae417e4eb70', max_length=200),
        ),
        migrations.CreateModel(
            name='SuccessStoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=85, size=[520, 400], upload_to='success')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.successstory')),
            ],
        ),
    ]
