# Generated by Django 3.1.2 on 2020-11-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20201114_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='1cdcaae6f66845ad9d97c95972b742258087a8e7febee809c34b6c54ac4ec413486f587a8703f8d74740099a5ba84ea17d8909a9cd982f98224449621e25fa94dbbc2e7125fba1e4b3ecacd118885cbcedd6c5c75fd56c00', max_length=200),
        ),
    ]
