# Generated by Django 3.1.2 on 2020-11-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20201114_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='22e3ed7b45b69faaa69a8c0cc49d6a0357701e9d1102dabc664f124c3a4cf02b2029f496e1a0f269430cdc800cfb7e0c6e21c384ddb3c6ff57f20cb794ffbbca8630c2bf2901cec008612d8788d4011f545085eac05b8e02', max_length=200),
        ),
    ]
