# Generated by Django 3.1.2 on 2020-11-28 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20201114_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='can_update_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='old_expiry',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='3826119f0ad7d535c41291bea6afb816ac69ed810a4791e9bb777f1fbe9bea9ad4b124a599163831dbbd27b9126d16376634171a4f9e855ec9c3974b1219a4026ee33ef5ccee4c09d68f3d6bd235ed2a27d4f9c5d75e48f8', max_length=200),
        ),
    ]
