# Generated by Django 3.1.2 on 2020-12-03 20:33

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20201128_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='5bd6e01e03f684e9615966707948c415fb205641005049dca1a02e43f09532326a809ddec375101ed693956a749b8d9305d5acbd7c7d28bb355e3b5ced476678cfc57ad781099f7ab040e19a332676778da32d766ab59761', max_length=200),
        ),
        migrations.AlterField(
            model_name='update',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=85, size=[380, 300], upload_to='updates'),
        ),
    ]
