# Generated by Django 3.1.2 on 2020-12-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20201203_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='24359f73c95fa566159e587720793b770501512576b7a6f21c71d1fc7cc5bd284ea56676da2f37e01ef18ed94d08234cc8d4dc443d20a736faffa36fdaa7c908ea5ab74d931dc5dfbeb2f293111926e0bf801016b6c79db7', max_length=200),
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
