# Generated by Django 3.1.2 on 2020-12-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20201204_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='0fa3a84a8095eb534be39ac233c089237fb9ff8b5ea63265d40bc2949c0813042cd93ff4ca26a99d69e7996213d0c008ed0e5f7d14aa6bc3199d7dace0a1f69c1d241d90d59c24bb84128e85271d4be316ac88430950daeb', max_length=200),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='details',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='update',
            name='details',
            field=models.TextField(max_length=600),
        ),
    ]
