# Generated by Django 3.1.2 on 2021-01-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20201207_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('f_name', models.CharField(blank=True, max_length=30, null=True)),
                ('l_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='11884ee3ddeac9cc98b6d8c5e35f34dfd160e42a3174a5178e704324ad37d0367fa540aa5237c8f973c69ff9495a25f691be883e255c5edccfbb3101aa7d94739252ef4a1ee6cbc4a1dd60ea86f6226af9f6cc403786d85b', max_length=200),
        ),
    ]
