# Generated by Django 3.1.2 on 2021-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20210113_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='trx_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donation',
            name='trx_msg',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='trx_ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='ca40335b7ba9f58d72d883fbc99d8c6ba3001786ac57e5f5c567f4ec470e00c6c3bc887ad8f925956a87bb53592214bdfc79587930a072ad3efa51c240b531ca702bb3cdd2d6c14265e0467061fe3ac7e835e6dcdd101264', max_length=200),
        ),
    ]
