# Generated by Django 3.1.2 on 2021-02-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20210219_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='withdraw_type',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='241041c218885c02e5d0ba687e502ce09ea6a1c28010dc7d51e9ce323490ad7cdf4a93669e8aac329d28018587b92571fc87e845abf57d3e076bc44c2409b9dc0cdc9cb4a362e5fbc6a987c8f24f8831ba62bf1a4edb05d6', max_length=200),
        ),
    ]
