# Generated by Django 3.1.2 on 2021-02-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20210219_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='75bcb9c06a3f7a732fbcfaa19b3693d0cf3f2db380f3f9fbdc9683b5e8617e2f9b7b4c0b44fd80282113218d0641d403030070d06559ae643772cec51c32f22a29440f81f80c57a69f1c01d9645f148541618577b6dbf86d', max_length=200),
        ),
    ]
