# Generated by Django 3.1.2 on 2021-03-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20210225_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='4a37340dd40ea4585c098f11653036b42a13f4959e9fecf9efd30e1affdfbcd46d5a9b85babd2dadd0aee221ae877a3db666128f86fa696eb82bfb34b2fd19cf5b612c3d4ab0e2ce0a20a2b6980cde5b46608f5c3ed289b6', max_length=200),
        ),
    ]
